jcmgray/quimb

- quimb/core.py
I've created a possible fix for the problem I raised in issue #17. The fix is that if ```len(dims) == len(inds)``` then ```pkron``` will set ```inds_out``` and ```dims_out``` to be empty tuples. Otherwise ```pkron``` behaves as before.
> Altered pkron so it allows number of ops to be the equal to len(dims)

- quimb/evo.py
- quimb/linalg/approx_spectral.py
- tests/test_linalg/test_approx_spectral.py
Instantiating Evolution with a ham that is a custom linear operator failed, because it tries to compute the Frobenius norm to set the first step-size. It ultimately failed on a call of the 'ravel' method.
This change allow for the norm to be estimated in this case
> Approximate norm in case of LinearOperator supplied to Evolution as the ham

- quimb/evo.py
- tests/test_evo.py
New parameter in the test_evo_ham test to check the time-dependent case. 
This doesn't really check an actual time-dependent example - it fakes a time-dependent Hamiltonian by wrapping a time-independent one as a callable so the the integrator gets called as if it were time-dependent.
This also adds some code to evo.py: If try to initialize Evolution with a time-dependent ham and a density op, raise a TypeError - the test checks this happens.
(Note: I think it should be possible to really implement time-dependent evolution of a density operator at some point).
> Add a simple test for the time-dependent Evolution code

- quimb/gen/operators.py
- tests/test_gen/test_operators.py
include a comprehensive test that hamiltonian_builder does what it says
> stop hamiltonian_builder coercing dtype if explicitly given

- quimb/evo.py
- tests/test_evo.py
- convenient to use solved system in callbacks
- if hamiltonian is time-dependent, it will be cached
and can be used for free by callbacks
Some repeated code in _setup_callbacks factored out in the process. Existing tests extended to cover these changes.
> Evolution: allow callback funcs to take in Hamiltonian

- quimb/evo.py
- tests/test_evo.py
also extend test to cover this
This is a small PR just to give access to the early-stopping mechanism of the underlying SciPy ode solver (depending on the output of solout)
> evo: allow early stopping for integration

- quimb/tensor/tensor_core.py
- tests/test_tensor/test_tensor_core.py
added an 'unfuse' method that changes the shape of specified inds.  Positions of new inds group are in the position of the old ind.  Ordering and shape of within new inds group is specified in the input parameters 'unfuse_map' and 'shape_map'.
> added an 'unfuse' method

- tests/test_tensor/test_tensor_gen.py
Misspelling in test_specials() parameter. It appeared that the test wouldn't run as intended with the misspelling.
> test_tensor_gen: fix parameter spelling

- quimb/tensor/circuit.py
This is a fix for issue #97.  It prevents TypeError when sampling random quantum circuits.
This fix was tested with 3 random quantum circuits.  Before this fix, the problem mentioned in #97 showed up in these circuits.
1. 72-qubit, depth=6
2. 80-qubit, depth=6
3. 90-qubit, depth=6
More circuits are tested after the this fix.  `sample` handled a 10x10-qubit, depth-10 case on RTX3090, while the program ran out of memory in 10x10-qubit, depth-20 case.
> fix TypeError in compute_marginal function

- docs/Makefile
- docs/_static/docset.css
- docs/conf.py
- docs/develop.rst
- setup.py
I added some instructions for automatizing the DocSet generation, which is used in documentation apps like Dash and Zeal.
It depends on `doc2dash >= 2.4.1` which should be soon released and it fixed a problem I had when using `doc2dash` with `quimb`.
Should I add `doc2dash >= 2.4.1` as a dependency for the `docs` extra requirements?
By the way, the site-location sidebar and the topbar unnecessarily take a significant amount of space in Dash, so I hide them with some CSS injection which I trigger with a `nobars` tag inside the `conf.py`:
https://github.com/mofeing/quimb/blob/9100da58321143532b27a8640107dff1dbdc0359/docs/conf.py#L178-L180
Thus, the `html` target has to be generated with the `-t nobars` flag. If you want to use the `html` documentation, the user has to rebuild it again. I …
> Generate DocSet using doc2dash

- quimb/tensor/tensor_2d_tebd.py
The `fit_strategy` parameter should be set to `autodiff-fidelity` instead of `autodiff` when trying to use an autodiff backend instead of ALS.
> Fix docstring regarding `fit_strategy` parameter for `FullUpdate` class.

- quimb/tensor/optimize.py
I'm trying to optimize a `TensorNetwork` with a list of `TensorNetwork`s as `loss_constant`, but it fails to parse them to constants.
The problem is that `parse_constant_arg` expects only a container of arrays (i.e. a `TensorNetwork`, a `Tensor`, a `list`/`tuple`/`dict` of arrays, or an array) and does not descend recursively.
This PR should fix it while keeping previous functionality intact.
> Fix `parse_constant_arg` for lists, tuples of `TensorNetwork`s

- quimb/linalg/approx_spectral.py
- quimb/tensor/tensor_builder.py
Fixed following deprecation warnings:
```
quimb/linalg/approx_spectral.py:11
/home/runner/work/quimb/quimb/quimb/linalg/approx_spectral.py:11: DeprecationWarning: Please use `uniform_filter1d` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
from scipy.ndimage.filters import uniform_filter1d
```
```
quimb/tensor/tensor_builder.py:824
/home/runner/work/quimb/quimb/quimb/tensor/tensor_builder.py:824: DeprecationWarning: invalid escape sequence '\s'
"""Construct a CP form hyper tensor network of the sum of matrix strings:
```
> Fix deprecation warnings

- quimb/tensor/tensor_builder.py
Encountered a bug where `.cnf` files couldn't be loaded if they contain empty lines (see below). 
Fixed by moving the empty line check up.
```
File ".../quimb/tensor/tensor_builder.py", line 2607, in cnf_file_parse
if args[0] == "p":
IndexError: list index out of range
```
> Fix empty lines in dimacs

- quimb/tensor/circuit.py
In the method `apply_gate_raw` of the class `Circuit`, the optional argument `gate_round` was input as a positional argument to the method `from_raw`. This resulted in a conflict with the positional argument `control`. Fixed by adding the parameter `gate_round` as a positional argument in `from_raw`.
>  apply_gate_raw: fix optional argument bug

- quimb/tensor/decomp.py
Details:
PennyLane has a new device ([`default.tensor`](https://github.com/PennyLaneAI/pennylane/blob/bec5bb0d8baa99a9e10fcce867a0160188ec6bdc/pennylane/devices/default_tensor.py#L147)) which can use quimb under the hood for the MPS and TN implementations. Currently, we observed a failure mode with a given circuit with the MPS backend:
```
import pennylane as qml
wires=62
layers=4
dev = qml.device("default.tensor", wires=wires)
@qml.qnode(dev)
def circuit():
for l in range(layers):
for i in range(wires):
qml.RX(0.1234,i)
qml.CNOT(wires=[i,(i+1)%wires])
return qml.expval(qml.PauliZ(0))
print(circuit())
```
For the above, and when setting OMP_NUM_THREADS to any value except that exact physical cores, we see the GESDD SVD method fail to converge (a [known …
> Bugfix: SVD fallback exception from numba compiled function

- quimb/tensor/circuit.py
- quimb/tensor/tensor_1d.py
- tests/test_tensor/test_circuit.py
- tests/test_tensor/test_tensor_1d.py
This adds efficient unbiased sampling to `MatrixProductState` and uses it by default in the `CircuitMPS` and `CircuitPermMPS` classes by default.
> add efficient MPS sampling, including to Circuit MPS classes

- quimb/tensor/circuit.py
- quimb/tensor/tensor_1d.py
- tests/test_tensor/test_circuit.py
- tests/test_tensor/test_tensor_1d.py
> fix MPS sample handling of RNG seed

- quimb/tensor/circuit.py
- tests/test_tensor/test_circuit.py
- tests/test_tensor/test_optimizers.py
> Add givens2 gate

- tests/test_tensor/test_tensor_core.py
`TestTensorNetwork.test_equalize_norms[42-float32]` fails when running with Python 3.13.x and the latest release.
Use a relative tolerance of `1e-5` instead of the default `1e-6` for the single precision case to avoid the test failure.
Fixes #328
> Relax equality tolerance for `float32` values
